### PR TITLE
Adds support for on-card session renaming

### PR DESCRIPTION
**Pull request by douglance**
Test with branch `friendly-name` of `phonon-client`

### CODE REVIEW

**Comment by maevyn11** [comment]
Testing this out, the name appears to be getting set on card correctly, but if I restart the app it goes back to displaying the CardID rather than the name in the frontend. Can we display the Name instead of the cardId on the lock screen and main page if it's available?

**Comment by maevyn11** [comment]
On second thought, we could merge this as is and add that display improvement in a separate PR.

**Comment by zerodouglas** [comment]
I noticed that when I click the unlock button, I click outside the dialog, I am unable to open the dialog again until I refresh the page. If I click the cancel button, I can re-open the dialog.

**Comment by douglance** [comment]
@zerodouglas Thanks for reporting that! Fixed in latest.

**Comment by zerodouglas** [comment]
Closing as this was included into a branch from the client and since has been merged.

**Comment by douglance** [comment]
@zerodouglas This branch isnt on `master` though??

**Comment by zerodouglas** [comment]
It should be in https://github.com/GridPlus/phonon-client/commit/53d85e54f3888172e65de7d3b50271cc785b1d7d ?

**Comment by zerodouglas** [comment]
Ah I see. Disregard, I miss read.

**Review by zerodouglas — APPROVED** [review]

**Pull request merged**
